### PR TITLE
more selective about what goes into zip + clean up

### PR DESCRIPTION
**Pull request by dmfenton**
Resolves https://github.com/koopjs/koop-opendata/issues/11

### CODE REVIEW

**Comment by dmfenton** [comment]
ping @chelm I tried to refactor the process a bit more but I got scared :dragon:

**Comment by chelm** [comment]
Yeah in need of tests on this very bad.

**Comment by chelm** [comment]
oh shoot @dmfenton did you update the Changelog too? :)

**Comment by dmfenton** [comment]
updated in master

**Pull request merged**
