### PR TITLE
V2.0.0

### PR DESCRIPTION
**Pull request by chelm**
Many changes here: 

* cleaner export zips,
* coded domain values in EsriJSON
* esri projection code look ups

The reason this v2.0.0 is due to the breaking change of removing tiles support from core...

### CODE REVIEW

**Comment by ngoldman** [comment]
@chelm since 1.1.2 was already published on npm we should probably keep it on the changelog and do the [YANKED] thing with it too. I made a release for it too.

Does [YANKED] or [DEPRECATED] make more sense? We're using actual npm deprecate and saying deprecated on https://github.com/Esri/koop/releases but I can change that to [YANKED] to be more consistent.

**Comment by chelm** [comment]
@ngoldman to me depricated makes more sense than YANKED in the changelog. I'll add 1.1.2 back as well

**Comment by ngoldman** [comment]
:+1:

**Comment by chelm** [comment]
@ngoldman when you're ready we should merge this, then cut a release and publish to npm

**Comment by ngoldman** [comment]
@chelm two things, both change log related:

Under 2.0.0, can you add:

```
### Removed
* tile support is no longer included by default, please use [koop-tile-plugin](https://github.com/koopjs/koop-tile-plugin) if needed
```

Also can you add this line back to the link references:

```
[1.1.2]: https://github.com/Esri/koop/compare/v1.1.1...v1.1.2
```

Otherwise the [1.1.2] link is borked and it just looks like brackets.

Other than that looks good to me.

**Comment by chelm** [comment]
@ngoldman done, will push up soon. I'm also testing one last thing with file exports for an open data bug.

**Comment by ngoldman** [comment]
ok looks good, here we go! :neckbeard:

**Comment by chelm** [comment]
sweet

**Pull request merged**
