### PR TITLE
remove errant pm2.json

### PR DESCRIPTION
**Pull request by ngoldman**
This PR removes the `pm2.json` file in `lib`. As far as I know this file shouldn't be checked into source control (checked with @chelm).

### CODE REVIEW

**Comment by dmfenton** [comment]
Perhaps not, but there needs to be a sample of this file somewhere. As well as docs about running workers in general.

**Comment by chelm** [comment]
@dmfenton yes to docs, but the workers and koop have nothing to do with PM2. It's merely a tool that Esri chooses to use to run its deploys.

**Comment by ngoldman** [comment]
@jwieringa is this something you need a copy of?

```
{
  "apps": [
    {
      "exec_mode": "fork_mode",
      "script": "./lib/ExportWorker.js",
      "name": "export-0",
      "node_args": [ ],
      "env": {
      },
      "error_file": "./lib/export-0.err.log",
      "out_file": "./lib/export-0.out.log"
    },
    {
      "exec_mode": "fork_mode",
      "script": "./lib/ExportWorker.js",
      "name": "export-1",
      "node_args": [ ],
      "env": {
      },
      "error_file": "./lib/export-1.err.log",
      "out_file": "./lib/export-1.out.log"
    }
  ]
}
```

**Comment by jwieringa** [comment]
@ngoldman no thanks, all set.

**Comment by ngoldman** [comment]
Alright thanks.

+1 on docs for running workers. If we end up needing `pm2.json` it's in this issue as well as source control but it sounds like it's just an artifact for now.

**Pull request merged**
