### PR TITLE
Export worker fixes

### PR DESCRIPTION
**Pull request by chelm**
This PR fixes issues with file names on large data exports and makes sure that the dataset status' get updated properly.

### CODE REVIEW

**Comment by chelm** [comment]
Ahh this test failed since koop-agol is not published yet. Fixing.

**Comment by chelm** [comment]
Hmm how do i get koop's npm module cache to use the latest npm version of koop-agol

**Comment by chelm** [comment]
ahh I see. The default route number is dependent on the configuration that the tests use.

**Comment by chelm** [comment]
this is ready to merge

**Comment by ngoldman** [comment]
@chelm you can use `npm cache clean` to clear the local cache, or just plain `rm -rf node_modules` and `npm i` to reinstall. If this change requires a certain version of koop-agol or higher I strongly recommend bumping the minimum version in package.json before publishing.

**Comment by chelm** [comment]
@ngoldman no I was just confused about the test and need to make this test less dependent on the config. Has nothing to do with Koop AGOL

**Comment by ngoldman** [comment]
Ah ok thanks clarifying

**Comment by ngoldman** [comment]
merged 👍

**Pull request merged**
