### PR TITLE
fix complexity

### PR DESCRIPTION
**Pull request by JerrySievert**
this fixes complexity reporting.

### CODE REVIEW

**Comment by ngoldman** [comment]
@JerrySievert pulled down your changes, `rm -rf node_modules && npm i`, still looks broken to me.

screen shot 2015-03-19 at 5 19 56 pm

**Comment by JerrySievert** [comment]
```
jerry@mewmew ~/w/koop (master)> gulp complexity
[17:57:27] Using gulpfile ~/work/koop/gulpfile.js
[17:57:27] Starting 'complexity'...
[17:57:27] Finished 'complexity' after 11 ms
jerry@mewmew ~/w/koop (master)> ls complexity/
complexity css        index.html js
```

give `gulp complexity` a try - let me know what you see.

**Comment by ngoldman** [comment]
@JerrySievert that does work. looks like it gets swallowed when the default task is run.

¯\\\_(ツ)\_/¯

**Comment by JerrySievert** [comment]
yeah, i noticed that.  i'm getting an error from gulp - like there's something stopping the reporter from running correctly.  i might see about updating versions of gulp, see if there's something else going on.

**Comment by JerrySievert** [comment]
looks like the `fail` portion of jshint was causing it to bail because of the linting errors.  i've removed the `fail`, for now, we need to get koop passing jshint regardless, but that shouldn't stop complexity metrics.

**Comment by chelm** [comment]
+1 on linting I'm halfway thought the errors

**Pull request merged**
